### ISSUE TITLE
Error provisioning win box from Vagrantfile

### ISSUE THREAD

**Issue by bogdananton** [bogdananton/phpunit-selenium-vagrant#7]
**Issue:**
When enabling `config.vm.provision :shell, path: "bootstrap.ps1"` then:

```
 ......
      default: Guest Additions Version: 4.2.16
      default: VirtualBox Version: 5.0
  ==> default: Running provisioner: shell...
  ==> default: Forcing shutdown of VM...
  ==> default: Destroying VM and associated drives...
  ==> default: Running cleanup tasks for 'shell' provisioner...
  /usr/lib/ruby/vendor_ruby/net/scp.rb:398:in `await_response_state': scp: /tmp/vagrant-shell: Error opening file: The requested operation failed. (RuntimeError)
    from /usr/lib/ruby/vendor_ruby/net/scp.rb:369:in `block (3 levels) in start_command'
    from /usr/lib/ruby/vendor_ruby/net/ssh/connection/channel.rb:311:in `call'
 ......
```

**Current Resolution:**
Run this PowerShell script manually from the shared folder: `\\VBOXSVR\vagrant\bootstrap.ps1` - takes at least 20 minutes.

**Reproduced on:**
Linux elv 4.2.0-19-generic #23-Ubuntu SMP Wed Nov 11 11:39:30 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by bogdananton** [comment]
Moved to https://github.com/bogdananton/Selenium-Setup-VM-Win7-IE11/issues/1
